name: ddcl_mbrl
channels:
  - nvidia
  - pytorch
  - conda-forge
  - anaconda
  - menpo
dependencies:
  - python=3.10
  - pytorch=2.4
  - torchvision
  - av
  - tensorboard
  - wandb=0.16
  - hydra-core=1.3
  - hydra-submitit-launcher=1.2
  - hydra-colorlog=1.2
  - imageio
  - imageio-ffmpeg
  - ffmpeg
  - moviepy
  - glew
  - mesalib
  - mesa-libgl-cos6-x86_64
  - glfw3
  - seaborn
  - matplotlib
  - pip
  - pip:
      - numpy==1.26.4
      - termcolor
      - jaxtyping
      - torchrl==0.4
      - tensordict==0.4
      - vector_quantize_pytorch
      - metaworld @ git+https://github.com/Farama-Foundation/Metaworld.git@master
      - dm_control==1.0.16
      - mujoco==3.1.2
